theme: jekyll-theme-cayman
title: Delano Johnson - Salesforce Technical Architect
description: Salesforce Technical Architect & Data Strategist with 12+ years building enterprise solutions
is_project_page: false




